import { SignalTable } from "@/components/SignalTable";
import { PerformanceSummary } from "@/components/PerformanceSummary";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function PerformancePage() {
    return (
        <div className="min-h-screen bg-background flex flex-col">
            <header className="border-b border-border p-4">
                <div className="container mx-auto flex items-center gap-4">
                    <Link href="/" className="text-muted-foreground hover:text-foreground transition-colors">
                        <ArrowLeft className="w-5 h-5" />
                    </Link>
                    <h1 className="text-xl font-bold text-foreground">Live Performance Log</h1>
                </div>
            </header>

            <main className="flex-1 container mx-auto p-4 md:p-8 space-y-8">
                <div className="space-y-2">
                    <h2 className="text-3xl font-bold tracking-tight">Signal History</h2>
                    <p className="text-muted-foreground">
                        Real-time log of all signals generated by our automated system.
                    </p>
                </div>

                <PerformanceSummary />
                <SignalTable />
            </main>
        </div>
    );
}
